
import string
import secrets

ans = input("Do you want to create a password ? Y/N" "\n")

if (ans.upper() == "Y"):
    length = input("How long you want yor password to be?" "\n" "Usually between 8 and 16 characters" "\n")
    if (length != string.digits):
        def randompassword(length):
            length = int(length)
            chars = string.ascii_letters + string.digits + string.punctuation    
            password = ""

            for x in range(length):
                password += secrets.choice(chars)
            return password
        password = randompassword(length)
        print("Your autogenerated password is: ", password)
        print("Thanks for using this software")

   
    else:
        print("You can only use numbers!")
else:
    print("Thanks for using this software")
   